package com.ceng316.ceng316_oims_backend.Documents;

public enum DocumentType {
    APPLICATION_FORM_TEMPLATE,
    APPLICATION_LETTER_TEMPLATE,
    REPORT_TEMPLATE,
    COMPANY_FORM_TEMPLATE,
    APPLICATION_FORM,
    APPLICATION_LETTER,
    REPORT,
    COMPANY_FORM,
    SSI_DOCUMENT,
    ANNOUNCEMENT
}
